# Ensures that only one deploy task per branch/environment will run at a time.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on: [push, pull_request]
name: Deploy Application
jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - uses: actions/checkout@v3
    - run: go test ./...

  release-linux-386:
    name: release linux/386
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Compile and upload release
      uses: StevenCyb/sc-go-cross-build@0.1.0
      with: 
        github-token: ${{ secrets.GITHUB_TOKEN }}
        platform: "linux/386"
        include-files: "README.md"
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Compile and upload release
      uses: StevenCyb/sc-go-cross-build@0.1.0
      with: 
        github-token: ${{ secrets.GITHUB_TOKEN }}
        platform: "linux/amd64"
        include-files: "README.md"
  release-linux-arm:
    name: release linux/arm
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Compile and upload release
      uses: StevenCyb/sc-go-cross-build@0.1.0
      with: 
        github-token: ${{ secrets.GITHUB_TOKEN }}
        platform: "linux/arm"
        include-files: "README.md"
